<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-EVD333TJ" failures="1" tests="1" name="Default test" time="8.11" errors="0" timestamp="02 Jul 2024 03:50:29 GMT">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="7.507">
    <failure type="java.lang.AssertionError" message="expected [THANKYOU FOR THE ORDER.] but found [THANK YOU FOR THE ORDER]">
      <![CDATA[java.lang.AssertionError: expected [THANKYOU FOR THE ORDER.] but found [THANK YOU FOR THE ORDER]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at SeleniumFramework.stepDefinition.StepDefinitionimpl.check_Confirmation_Message_Is_Displayed(StepDefinitionimpl.java:49)
	at âœ½."THANK YOU FOR THE ORDER" message is displayed on the Confirmation Page.(file:///C:/Users/wwwde/OneDrive/Desktop/selenium_Project_Workspace/SeleniumFrameworkDesign/src/test/java/SeleniumFramework/Cucumber/PurchaseOrder.feature:14)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Default test -->
